To Do List
Fayob/To-Do-List-Project pull request #2
Opened 2022-09-28 21:19 UTC by Fayob

## TO DO LIST TASK

- setup linters
- set up webpack
- ignore file in gitignore
- add mark up file
- add styles file
- add javascript file

2022-09-28 22:00 UTC, m05e5 requested changes
Hi @Fayob  , 

Good job so far. I really like what you did!
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] Please see comments bellow

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 22:00 UTC, m05e5 commented on src/modules/edit_task.js
> +};
- [ ] Well done with the edit. As mentioned in the requirements,  all changes in your todos should be saved in local storage. kindly save the todo in local storage after exit

2022-09-28 22:00 UTC, m05e5 commented on src/modules/add_task.js
> +
- [ ] Actually when we add some todos, delete one and add another one as you can see some todos comes out with the same index. This creates issues when we now delete one of the todos with same index. please kindly consider and fix it
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/37901469/192895853-35d57b42-e66c-4dea-a52e-8adc73fd7618.png">

2022-09-29 11:34 UTC, roshan-bajgain approved these changes
Hi @Fayob, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 12:34 UTC, merged